spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qorikusi_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  jackson:
    default-property-inclusion: non_null

http:
  client:
    cart:
      url: http://localhost:8083/cart/
    product:
      url: http://localhost:8082/catalog/

security:
  jwt:
    secret: "xtIrmdnwz1LKSsAo12U2TV8xVgw4r7LDQrxjlh+ToM3XUqhiVl+xlz0ec6RytSgbA+5CVoGMt441OtJxGKAWTw=="